### ISSUE TITLE
Cant find the add-on on integrations after install

### ISSUE THREAD

**Issue by daboshman** [amosyuen/ha-tplink-deco#100]
## Debug log

```text

Add your debug logs here.

```
I tried install manually and also with Hacs and the integration cannot be found.
I am on vesion Home Assistant 2022.9.0

**Comment by amosyuen** [comment]
As far as I can tell from my installation and other people who have installed it, it works fine through HACS. Please verify that your HACS is installed correctly.

1. Can you find and install other integrations through HACs fine?
2. How are you searching for the integration? "Are you searching using "deco" in the right UI?
