### ISSUE TITLE
Incompatible with Firmware 1.6.0 on M9Plus

### ISSUE THREAD

**Issue by werehamster999** [amosyuen/ha-tplink-deco#107]
Hi,

 Just on the off-chance it's not been noticed. The v1.60 firmware that's currently in public beta for the M9's has significant rewrites and the Luci web API calls have either been blocked, moved or removed ("Illegal URL" in the Router's logs). It's a show stopper unfortunately. The M5's and M4's all have similar code so some re-writes are ahead :-(

This link below should show the forums entries for items tagged with "New Firmware" in case you want to have a look.

 https://community.tp-link.com/en/home/forum/39?tagId=672&labelIds=8214

 If I can work out how, I'll try and unpack an image :-)

 Regards,
Keith

**Comment by werehamster999** [comment]
Ignore me!

  The main router needed another re-flash and just hadn't set up the Web service correctly.  At the moment, it's working fine, yippee! Some of the forum posts have mentioned duplicate entries on different nodes for connected devices but it's on the list for a fix.

 Phew!

**Comment by amosyuen** [comment]
Glad you figured it out
