### ISSUE TITLE
Cannot connect to host 

### ISSUE THREAD

**Issue by abeksis** [amosyuen/ha-tplink-deco#108]
I get error messages in login since the last update. what could be the problem?

I re -tried to be foam and the same problem.

[[Imgur](https://imgur.com/AnUabj3)](https://imgur.com/AnUabj3)

**Comment by dkwolf1** [comment]
Me neither. Deleted the integration but can't get it back to work. Get an invalid error while setup

**Comment by amosyuen** [comment]
Please follow steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by dkwolf1** [comment]
2022-10-01 09:55:00.222 ERROR (MainThread) [custom_components.tplink_deco] List Clients 34-60-F9-58-6D-80 client response error: 500, message='Internal Server Error', url=URL('http://192.168.1.1/cgi-bin/luci/;stok=73b91bb5cb8a1a32686d426fd2112df2/admin/client?form=client_list')

2022-10-01 09:54:58.966 WARNING (MainThread) [custom_components.tplink_deco] Error testing credentials: 500, message='Internal Server Error', url=URL('http://192.168.1.1/cgi-bin/luci/;stok=73b91bb5cb8a1a32686d426fd2112df2/admin/client?form=client_list')

I found these, error testing credentials. I login with admin and my password

**Comment by amosyuen** [comment]
Your deco is giving an internal error. Please follow the advanced debugging steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by DravenSA** [comment]
> Your deco is giving an internal error. Please follow the advanced debugging steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

and then what?

**Comment by copetogo** [comment]
i am getting error while setting up the integration. saw this in the logs
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:81
Integration: TP-Link Deco (documentation, issues)
First occurred: November 15, 2022 at 5:14:38 PM (16 occurrences)
Last logged: 11:17:11 AM

Error testing credentials: 404, message='Not Found', url=URL('http://192.168.1.1/cgi-bin/luci/;stok=/login?form=keys')
Error testing credentials:

**Comment by amosyuen** [comment]
@copetogo either your host IP is incorrect or your deco doesn't use the same auth as this integration. You can check what calls your admin page does by following advanced debugging instructions at https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by copetogo** [comment]
> https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

ok i went through all the calls none of them pinged. So what do you mean by same auth as integration ![Screenshot 2022-11-17 at 6 49 24 PM](https://user-images.githubusercontent.com/96839787/202457370-f2715145-8451-4446-bff1-f92d9996e9a0.jpg)

**Comment by amosyuen** [comment]
Why is your auth page in the browser (192.168.1.46) a different IP address than configured for the integration (192.168.1.1)?

The integration just sends a series of HTTP calls that match the calls made on the admin login page. Most of the decos use the same series of HTTP calls so it should work for them.

If you aren't seeing a call such as `http://<ip_address>/cgi-bin/luci/;stok=/login?form=keys` in the browser debugger network tab, then that probably means TP-Link has implemented some new auth that uses a different series of HTTP calls. If that's the case the integration won't work for you. Theoretically we could reverse engineer the new series of auth calls, but it can be difficult depending on what kind of encryption they are using. But likely that would require a lot of work which I can't commit to now.

What's your deco model? For now I can list that model as unsupported.

**Comment by copetogo** [comment]
> Why is your auth page in the browser (192.168.1.46) a different IP address than configured for the integration (192.168.1.1)?
> 
> The integration just sends a series of HTTP calls that match the calls made on the admin login page. Most of the decos use the same series of HTTP calls so it should work for them.
> 
> If you aren't seeing a call such as `http://<ip_address>/cgi-bin/luci/;stok=/login?form=keys` in the browser debugger network tab, then that probably means TP-Link has implemented some new auth that uses a different series of HTTP calls. If that's the case the integration won't work for you. Theoretically we could reverse engineer the new series of auth calls, but it can be difficult depending on what kind of encryption they are using. But likely that would require a lot of work which I can't commit to now.
> 
> What's your deco model? For now I can list that model as unsupported.

So to answer why my ip is different is because my decos are working in Ap mode . So my main deco is connected to via Ethernet to isp router and remaining decos via Wi-Fi. So the IP will be 192.168.0.1 or 192.168.1.1 will only be if the deco  is being operated as main router . So is this a way of telling this integration only works if the deco acts as the main router . My deco model is S7 although it does not show in your supported list but I am not inclined to believe incompatibility is not an issue since support page shows compatibility with S4 but thanks for your advice anyways

**Comment by amosyuen** [comment]
> So to answer why my ip is different is because my decos are working in Ap mode . So my main deco is connected to via Ethernet to isp router and remaining decos via Wi-Fi. So the IP will be 192.168.0.1 or 192.168.1.1 will only be if the deco is being operated as main router . So is this a way of telling this integration only works if the deco acts as the main router . My deco model is S7 although it does not show in your supported list but I am not inclined to believe incompatibility is not an issue since support page shows compatibility with S4 but thanks for your advice anyways

That's right that you should always be using the main deco IP address with the integration. Assuming you followed the advanced debugging instructions correctly and you saw none of those HTTP calls in the history then that indicates it's using different http call paths. If you want to verify, you should post a screenshot / list of the HTTP calls made.
