### ISSUE TITLE
Name: 'utf-8' codec can't decode bytes

### ISSUE THREAD

**Issue by zwrose** [amosyuen/ha-tplink-deco#122]
## Version of the custom_component
v2.2.3

## Deco Model

Deco X60

## Describe the bug

On integration setup, after entering in credentials/host/etc (checked multiple times), the integration fails with an error message "Unexpected error"

Based on the surrounding log messages, it looks like auth was successful, client lists are being pulled successfully, but there's issue parsing. 

In the logs below, I didn't include the long client list in the error because it looks like it has private info there (lots of mac addresses, names encoded in some way), so I didn't want to include it broadly here...

## Debug log

```text
2022-12-04 22:04:32.563 ERROR (MainThread) [custom_components.tplink_deco] List Clients C0-C9-E3-03-18-B4 parse response error='utf-8' codec can't decode bytes in position 1-3: invalid continuation byte, data={//data omitted since it looks to have private info}

2022-12-04 22:04:32.573 ERROR (MainThread) [custom_components.tplink_deco] Unexpected error fetching tplink_deco-clients data: 'utf-8' codec can't decode bytes in position 1-3: invalid continuation byte
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/tplink_deco/coordinator.py", line 242, in _async_update_data
deco_client_responses = await asyncio.gather(
File "/config/custom_components/tplink_deco/coordinator.py", line 45, in async_call_with_retry
return await func(*args)
File "/config/custom_components/tplink_deco/api.py", line 216, in async_list_clients
raise err
File "/config/custom_components/tplink_deco/api.py", line 211, in async_list_clients
client["name"] = base64.b64decode(client["name"]).decode()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-3: invalid continuation byte


```

**Comment by bartlebyxxx** [comment]
I have the same problem. I had the integration Installed for a while but noticed an error, so i tryed retting it up from scratch and got the error. This happened right after TP released the new looking interface (At least when I saw it the first time)

**Comment by HaWeGithub** [comment]
I have the same problem. Also happened right after TP firmware upgrade.

**Comment by amosyuen** [comment]
My deco hasn't gotten a firmware update so I'm unable to repro. Are any of you able to determine what the bad "name" field looks like from the long client list?

**Comment by arnoldpronobis** [comment]
Deco M4, same problem after update - "Unexpected Error"

**Comment by zwrose** [comment]
finally had some time to dig into this further and was able to work around the issue. The bad name was `R9vu4Rg=`; in the Deco app UI it was garbage characters. I renamed the device (not actually sure what it is...) in the Deco UI and that resolved the error! 

I was able to identify the bad name by looking at the data field in the error and finding the first one in the list still showing as b64 encoded (the other items earlier in the list were no longer encoded).

@amosyuen a potential improvement consideration could be to more defensively handle bad characters (maybe the firmware update from Deco makes them more common?) and e.g. replace decoding failures with some safe placeholder? not sure how feasible that would be.

**Comment by amosyuen** [comment]
@zwrose Sounds reasonable. Fix is in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.2.4

**Comment by arnoldpronobis** [comment]
Deco M4, "Unexpected Error" still present, version 2.2.5

**Comment by amosyuen** [comment]
@arnoldpronobis  this is not an issue for "Unexpected Error" this is an issue for name decoding error.
