### ISSUE TITLE
Error testing credentials: Login error_code=-5003

### ISSUE THREAD

**Issue by SgtFoose** [amosyuen/ha-tplink-deco#126]
[TP-Link Deco HA Error LOG .txt](https://github.com/amosyuen/ha-tplink-deco/files/10269428/TP-Link.Deco.HA.Error.LOG.txt)

Error:
Unexpected error fetching tplink_deco-decos data: Login error_code=-5003
Login error_code=-5003, data={'result': {'failureCount': 10, 'attemptsAllowed': 0}, 'error_code': -5003}

Main deco mode: M5(1.0)
Firmware: 1.6.1 Build 20220818 Rel. 36456

Tried:
Direct browser access to 192.168.178.128 with no username (asume this is admin) and my deco password.
This succeeds with no problems.

Test with both Enable and Disable SSL, same result.

**Comment by SgtFoose** [comment]
Guess what, this morning I tried connecting to one of my M4's instead if the MAIN M5 and it worked but no entities.
Switched the IP in my configuration to the main and now all is great!

**Comment by amosyuen** [comment]
There doesn't seem to be clear documentation on error code -5003. But glad that worked out for you.

**Comment by jaimzm** [comment]
In case someone else comes across this, I was getting exactly the same error on my X20s. Simply restarting the Decos immediately solved the issue for me.
