### ISSUE TITLE
Possible to monitor client connected to AP?

### ISSUE THREAD

**Issue by SgtFoose** [amosyuen/ha-tplink-deco#128]
Hi,

I'm using this integration but I'd like to know if it's possible to monitor a specific client to see to which Access point
he/she's connected. I have 5 AP's but sometimes have complaints about slow wifi.
When monitoring Deco, I see my wife's iPhone is connected to a remote AP while a new unit is nearby.
I know this is a Roaming / Firmware issue but like to use Home Assist to get a better picture of my house.
Maybe this module can help me achieving this with repositioning Access Points or buying extra.

**Comment by amosyuen** [comment]
You can see which deco is connected by looking at the `deco_device` attribute on the client. See the https://github.com/amosyuen/ha-tplink-deco.
