### ISSUE TITLE
Integration should not use custom device_class

### ISSUE THREAD

**Issue by frenck** [amosyuen/ha-tplink-deco#136]
### Problem

This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

### TP-Link Deco Version

all

### Router Model

n/a

### Debugging Information

n/a

**Comment by amosyuen** [comment]
Thanks for notifying, will take a look

**Comment by amosyuen** [comment]
Guessing you just did a regex search, but seems that any `DEVICE_CLASS_` references are for custom device classes I've defined and are not reference to HA device classes. See https://github.com/amosyuen/ha-tplink-deco/blob/master/custom_components/tplink_deco/const.py

**Comment by frenck** [comment]
Do you mean these?

![CleanShot 2023-01-06 at 09 57 27](https://user-images.githubusercontent.com/195327/210966941-810599b1-436c-48ce-a459-4d78a98f21b2.png)

Those are not valid device classes?

If you need custom device classes, they "could" be prefixed with the domain, e.g., 

`tplink_deco__my_class`

Are they used for translations? If so, that doesn't need device classes anymore.

../Frenck

**Comment by amosyuen** [comment]
It's just used to help users differentiate between clients and routers

**Comment by frenck** [comment]
> It's just used to help users differentiate between clients and routers

That is not what device classes are for. Device classes are a strict set which are defined here:

<https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes>

Since custom device classes (domain prefixed) for translations aren't needed anymore (see https://developers.home-assistant.io/blog/2022/12/01/entity_translations), it means that we have been working on enforcing this set as well.

Work on this has started last December, see: <https://github.com/home-assistant/core/pull/83391/files#diff-f864c7480678e548519b8ba7f8dd17d8dfd2518f04a231b6553f277d54bd110d>

These custom, non-existing device classes will eventually result in errors.

../Frenck

**Comment by amosyuen** [comment]
Fixed with latest changes

**Comment by frenck** [comment]
Nice! Thanks! 🎉
