### ISSUE TITLE
Feature request: action to trigger polling immediately 

### ISSUE THREAD

**Issue by Pauligrinder** [amosyuen/ha-tplink-deco#144]
Hi!

I have a little feature request: make a callable service similar to tplink_deco.reboot_deco that immediately checks comnection status of devices. 

I guess it could also take specific devices as parameters to only check the specified ones (maybe that would be faster, the M4 at least seems to respond very slowly when refreshing everything).

The idea is that I would hook this up to a motion detection event in order to detect who came home for example, and then the automatic polling of the integration could be disabled instead.

Should be relatively simple to do, right? 

I could even do it myself at some point, I guess.

**Comment by amosyuen** [comment]
https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity should do what you want. Only need to call it on a single entity from the integration and it should update all of them.
