### ISSUE TITLE
How to create a different account to access the app and how to show the routers in lovelace?

### ISSUE THREAD

**Issue by Gferretta** [amosyuen/ha-tplink-deco#147]
Hi everyone

I have several TPLink DECO M4R installed

The integration works very well, only sometimes it gives me an error and it's because I use the same account in the app and in HA.
The issue is that I can't find where/how to create an administrator account to use in the app.

My other question is how to show the routers with their connected clients in lovelace, since the clients are dynamic and connect or disconnect, so not just any card will work.    Which one do you use?

Thank you
Regards

**Comment by amosyuen** [comment]
Instructions were added at https://github.com/amosyuen/ha-tplink-deco#login-credentials. I don't display the connected clients in lovelace but you can try something using https://github.com/thomasloven/lovelace-auto-entities

**Comment by Gferretta** [comment]
Both suggestion work great!
No more disconnection with the new admin user and lovelace work tremendous with thus HACS interface.
Thanks very much for your work and patient.
