### ISSUE TITLE
Timeout fetching data, most devices disabled

### ISSUE THREAD

**Issue by ctkcoding** [amosyuen/ha-tplink-deco#15]
## Version of the custom_component
ha-tplink-deco v0.0.1
running on a pi 4b with armv7
home assistant version: core-2022.2.0.dev20220118
Installation Type | Home Assistant Container
Python Version | 3.9.7

## Timeout/nonetype issue logs
```
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: helpers/update_coordinator.py:193
Integration: TP-Link Deco (documentation, issues)
First occurred: 8:11:05 AM (1 occurrences)
Last logged: 8:11:05 AM

Timeout fetching tplink_deco data
```

## custom component logs
```
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/coordinator.py:119
Integration: TP-Link Deco (documentation, issues)
First occurred: 8:11:25 AM (1 occurrences)
Last logged: 8:11:25 AM

Error calling on_close function <function async_dispatcher_connect.<locals>.async_remove_dispatcher at 0xa99e4ad8>: object NoneType can't be used in 'await' expression
```

## Describe the bug
The integration on 0.0.1 will successfully install through hacs and looks like it successfully configures on the integrations page but then immediately after the success message, the list of devices on my deco will be pulled but almost all devices are disabled. I have 40 entities but only 14 devices because so many devices on my wifi have been found but are disabled, seemingly from this timeout. There are no other errors popping up except these. I'm interested in helping with the fix but I'm not sure where to start

**Comment by amosyuen** [comment]
Could you clarify, by disabled, do you mean `unavailable` or that mean "Enable Entity" is off)? 
![image](https://user-images.githubusercontent.com/422794/150418967-770d5448-7dc3-4969-ab18-2c4500ca31d0.png)

I think there are a couple of things going on here:

- Since the log said "First occurred: 8:11:05 AM (1 occurrences)" sounds like it only happened once. If it's happening a lot then that's a problem, but once is fine.

- The custom components logs looks like an actual bug, but that's unrelated to the timeouts and disabled entities. I'll send a fix for that, but should be unrelated as it only happens when integration is removed.

**Comment by ctkcoding** [comment]
Thanks for taking a look. I don’t know if it’s happening multiple times but it seems like it doesn’t check again because all the disabled entities are disabled by the integration so I think the answer to your question is both. The weird thing is some devices are shown as available and active and some are totally unavailable but they are all listed as entities just the unavailable ones aren’t listed as devices, if that makes sense. I’m attaching a screenshot of another one’s history to show that some are working fine. The ones that show up properly are all tp link Kasa switches and plugs that I’ve already added through the Kasa integration, but this deco integration is still adding the info that I would expect based on the deco docs if that helps and makes sense

**Comment by ctkcoding** [comment]
![629ECE69-A697-4EE9-91AA-F00AC208A028](https://user-images.githubusercontent.com/43896808/150434890-50a66f9d-c94e-4b8d-adcd-85ff4a0cfe94.png)
![80B9E2A5-55A9-4AB7-ACAB-98E43D8167A1](https://user-images.githubusercontent.com/43896808/150434894-7eb1a86d-60f9-4d14-9496-fe8208798029.png)
![0524BC49-7067-4FF6-8943-25644FD14151](https://user-images.githubusercontent.com/43896808/150434898-55739105-d357-4a26-a219-53cbe8af7d7e.jpeg)
It looks like the email upload didn’t work. I’m also adding a screenshot from my ha integrations page to show the difference between the and device’s counts

**Comment by amosyuen** [comment]
Hmm, that is quite strange, because there shouldn't be any devices, only entities. My code doesn't specify any `device_info`, so there should not be any associated devices.

My integration view:
![image](https://user-images.githubusercontent.com/422794/150439893-5439bfe7-9609-4f3d-acfd-d285773e41e4.png)

I'm curious what the devices look like? Could you get a screenshot? Particularly interested in:
- How are they named and does it look correct (e.g. Chris Laptop)?
- What entities connected to the devices?

**Comment by ctkcoding** [comment]
Let me take a look tonight and send some more screenshots. I guess it has the devices because it’s linking the TP-link Kasa devices with their entities from the deco integration but I have no clue how it’s linking, maybe just name? Also weird thing if it’s supposed to only be entities - it looks like only the devices have the deco attributes that the deco integration specifies is mac address

**Comment by amosyuen** [comment]
So I'm using the mac address as the entity unique ID, there's a good chance that the other Kasa integration is also doing that. In that case, HA is maybe merging them or something. I think the solution is for me to use a different unique ID.

**Comment by amosyuen** [comment]
Looks like that is the case at https://github.com/home-assistant/core/blob/f72bf2145b7e310f34f23ad34f8294d8fe1360ce/homeassistant/components/tplink/__init__.py#L243

**Comment by ctkcoding** [comment]
That makes sense to me for how they’re merging but why would the entities be disabled for ones that don’t match the tplink Kasa integration? They should still be available but just not merged, right?

**Comment by ctkcoding** [comment]
I just manually enabled some of the “unavailable” entities and they look ok now. Ok as in they are displaying the attributes that your deco integration says should be picked up from the deco wifi. Did I miss something in the readme about manually enabling the entities for wifi clients I want to track? It seems like I just got mixed up with how to manage on the ui, and the code is all good. If this needs an update on readme I can write something out and add an image or two for future users  reference

**Comment by ctkcoding** [comment]
Just to be clear I do not have an issue with the mac address id overlap causing devices to show up, because those actually were working immediately. The ones without Mac id overlap are the ones that were problematic but now knowing to manually enable those entities it seems like it’s all working fine. I can make a PR to automatically track the entities and/or update the readme to explain for new users if they encounter a similar issue

**Comment by amosyuen** [comment]
You shouldn't need to manually enable the entities, they should be enabled by default. Not really sure why they are disabled.

Could you confirm if the entities that were disabled are the non-merged ones?

Assuming it's not really a problem, I'll probably leave the `unique_id` alone then.

**Comment by scooper1** [comment]
I have a similar problem  with all entries almost immediately   going unavailable

**Comment by TTLucian** [comment]
I'm not sure if it's related but all devices are unavailable and error in log
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tplink_deco/coordinator.py:72
Integration: TP-Link Deco (documentation, issues)
First occurred: 5 February 2022, 15:23:02 (1 occurrences)
Last logged: 5 February 2022, 15:23:02

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/__init__.py", line 130, in update_listener
    await async_reload_entry(hass, entry)
  File "/config/custom_components/tplink_deco/__init__.py", line 116, in async_reload_entry
    await async_setup_entry(hass, entry)
  File "/config/custom_components/tplink_deco/__init__.py", line 82, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = await async_create_coordinator(hass, entry, api)
  File "/config/custom_components/tplink_deco/__init__.py", line 61, in async_create_coordinator
    coordinator = TplinkDecoDataUpdateCoordinator(
  File "/config/custom_components/tplink_deco/coordinator.py", line 72, in __init__
    update_interval=timedelta(seconds=scan_interval_seconds),
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by amosyuen** [comment]
That's unrelated, not sure how you got into that state, but looks like I need to make those values required in the config.

**Comment by amosyuen** [comment]
I've had trouble reproing, so I'm not enitrely sure, but I suspect that the initial query is failing and so the integration is loaded in a failed state, which might cause all the entities to be added as unavailable.

In https://github.com/amosyuen/ha-tplink-deco/releases/tag/v1.0.1 I've added a retry for expired auth and timeouts which should help mitigate this.

**Comment by ctkcoding** [comment]
I wonder if there is some issue just on the 32bit pi. That’s where I initially saw this issue and had to go and manually enable devices/entities. I will try on a higher power server that runs x86_64 and see if that has the same issue. I know there were docker containers that failed on the 32 bit pi. I’ll post an update when I’ve tried on my 64bit intel

**Comment by amosyuen** [comment]
Closing the issue as haven't received further reports
