### ISSUE TITLE
Why do other devices appear in the integration?

### ISSUE THREAD

**Issue by Gferretta** [amosyuen/ha-tplink-deco#153]
Hello
I am noticing that without an established logic, sometimes it detects 1 or more devices that belong to another integration (SonOffLAN)
To remove them and leave only the DECO I have to uninstall the DECO integration, reboot HA and then reinstall the DECO integration.

Any ideas?

I leave a screenshot, with 1 device in this case, but yesterday there were 3.
![TPLink and Sonoff](https://user-images.githubusercontent.com/65413059/216820209-06fd4172-7b51-444c-b192-c98fd23c76f6.jpg)

Regards

**Comment by amosyuen** [comment]
https://github.com/amosyuen/ha-tplink-deco/issues/73
