### ISSUE TITLE
Invalid authentication error when adding device

### ISSUE THREAD

**Issue by brianqtb** [amosyuen/ha-tplink-deco#155]
### Problem

Unable to add device. Followed the instruction to create new manager. Exiting all apps as documented. But got an "Invalid authentication"

### TP-Link Deco Version

v1.5.1 Build 20210204 Rel 50164

### Router Model

Deco X60

### Debugging Information

Unable to setup debugging. Check configuration fail after appending documented logging procedure

**Comment by brianqtb** [comment]
Tried setting up debug, based on documentation. When 'Check Configuration', I had an error 'Configuration invalid!' with the system prompting me "Integration error:logs - Integration 'logs' not found". Not sure what to do?

**Comment by amosyuen** [comment]
Sorry, looks like indentation was incorrect in debugging docs. I've updated it with the right indentation.

**Comment by brianqtb** [comment]
[home-assistant_2023-02-07T07-16-10.553Z.log](https://github.com/amosyuen/ha-tplink-deco/files/10672495/home-assistant_2023-02-07T07-16-10.553Z.log)
Still not working.

**Comment by brianqtb** [comment]
Managed to solve the problem.
