### ISSUE TITLE
Timeout fetching tplink_deco-clients data

### ISSUE THREAD

**Issue by Gferretta** [amosyuen/ha-tplink-deco#156]
Hi.  
I clarify that I have the owner user in HA and a different administrator user in the app.  
I have noticed that the integration does not bring all the devices connected to the DECO routers and that, in addition, there are no updates of the up / down connections.  
I am receiving the attached error very often.  
I have searched the site and found nothing to test.  
Thank you
Regards

![SmartSelect_20230206_211053_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/217254800-73737af2-414b-47a9-b297-93c91079f3e8.jpg)

**Comment by amosyuen** [comment]
Most likely that is an error from your router. To confirm, you should login to the admin portal look at the clients and open network deubgging and see if the client fetch is timing out. If so, there is nothing I can do.

You could try rebooting your router and see if that helps.

**Comment by Gferretta** [comment]
> Most likely that is an error from your router. To confirm, you should login to the admin portal look at the clients and open network deubgging and see if the client fetch is timing out. If so, there is nothing I can do.
> 
> You could try rebooting your router and see if that helps.

I'm try
Thk

**Comment by amosyuen** [comment]
Timeout seconds and timeout retries config has been added as a mitigation in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0
