### ISSUE TITLE
Reporting offline when online

### ISSUE THREAD

**Issue by StrandmonYellow** [amosyuen/ha-tplink-deco#157]
### Problem

My device is clearly online (showing connected via wifi on my phone and in the tp-link app) but the entity shows not_home. Am I doing something wrong?

### TP-Link Deco Version

1.4.9 (latest version)

### Router Model

Deco P7

### Debugging Information

![error tp link](https://user-images.githubusercontent.com/99552124/217523312-8a166631-ed5a-4d41-a021-34139e69807f.png)

**Comment by amosyuen** [comment]
Follow https://github.com/amosyuen/ha-tplink-deco/blob/main/DEBUGGING.md and get debug logs for the list clients. If the data there does not list the device, then that's what the deco returns.

**Comment by adi170-alt** [comment]
same issue I think, I have that it is sometimes for a few minutes 1-15 minutes, I have increased the timeout seconds, maybe that will help.


> Follow https://github.com/amosyuen/ha-tplink-deco/blob/main/DEBUGGING.md and get debug logs for the list clients. If the data there does not list the device, then that's what the deco returns.

There are no errors in de log, I will maybe try later the additional debugging.

**Comment by amosyuen** [comment]
Closing because no debug logs
