### ISSUE TITLE
Populate deco_device and deco_mac for deco device trackers

### ISSUE THREAD

**Issue by Gferretta** [amosyuen/ha-tplink-deco#160]
Hi
The integration is working very well for me.
I would like to know if it is possible to know for the DECOs that have **master: false**, to know what other DECOs they are connected to.
More than anything to know if for some reason the network has been misconfigured.
In the TPLINK app that is seen _graphically_.

I think these 2 attributes would be missing for the **device_type: deco**
```
deco_device:
deco_mac:
```

Thank you
Regards

**Comment by amosyuen** [comment]
Added in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.4.0
