### ISSUE TITLE
New Host IP Address Not Saving

### ISSUE THREAD

**Issue by zwrose** [amosyuen/ha-tplink-deco#161]
My Deco's are used in Access Point mode, and as a result it's possible for the Host IP Address to change. This happened to me recently, and I've seemed to encounter an issue with this integration now where the Host IP Address does not "stick" when saving upon reconfiguration.

Steps I take:

1. Go to Integrations section
2. See the integration failing because it's trying to talk to the old IP address which is no longer a Deco
3. click Configure
4. Change Host to new, correct IP address
5. Get a success message
6. See in the debug logs that devices were indeed fetched

Expected behavior - integration is back working again

Actual behavior - the integration reverts back to trying to reach the old, bad IP address. When I open the configuration menu again, the old IP address is there again.

I've tried both quickly "reloading" the integration after the successful reconfiguration, and doing nothing - in both cases, it reverts to attempting to contact the old, bad IP address.

Not sure there are any logs that would be useful here, but let me know if there is something it would be good to see. The only debug logs I see are either ones related to the successful one-time sync at the time of reconfiguration, and otherwise, the message that the call to the bad IP fails (and the clear_auth call)

**Comment by boberggreen** [comment]
I got exactly same problem with my Deco M5 in my HA. IP Address is change, and when i save I get success but the old IP is still there

**Comment by zwrose** [comment]
@amosyuen - any thoughts on this one?

**Comment by amosyuen** [comment]
I'm not able to repro, changing IP address works for me. Make sure you're on the latest version, and maybe try installing from scratch. Possible that there's a problem with upgrading from older versions.

As an aside you should set a static IP assigment for the deco mac so that you don't need to keep updating it.

**Comment by lyzo** [comment]
When changing IP adres, then I got also a succes message. But it still use the old IP adres.

My solution was, reinstall the integration.

**Comment by amosyuen** [comment]
Finally tracked this down, I had trouble re-proing since my config was already initialized. It only reproed if the config failed to initialize on startup. Fix is in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.5.5
