### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by Sarnog** [amosyuen/ha-tplink-deco#165]
Hello,

Is it possible, to get an option to add coordinates in the tracker entity? This way i don't get troubles when i use "person.entity" as a tracker, that some automations or integrations fail, because they don't get coordinates when i'm connected to my home network's wifi.

Thanks in advance!

Greetings,

Sarnog.

**Comment by amosyuen** [comment]
No plans to do this as there are no coordinates and this is the correct state. Please request the problematic automations and integrations to take into account device trackers without coordinates.
