### ISSUE TITLE
Idea: total kB/s Up and Down per Deco device

### ISSUE THREAD

**Issue by Verguldebarman** [amosyuen/ha-tplink-deco#166]
I have created several template sensors in HA to show the total Up- and Downstream in kB/s per Deco device. Perhaps this is an idea to add into te integration. 

Template Sensor looks like this for total Upload for <deco_name>:

```
- platform: template
  sensors:
    deco_<deco_name>_up:
      friendly_name: "Deco <deco_name> Upload kB/s"
      icon_template: mdi:server-network      
      unit_of_measurement: kB/s
      value_template: |
        {% set ns = namespace(result=0) %}
        {% set array = integration_entities('tplink_deco') | list %} 
        {% for a in array if state_attr(a, 'deco_device') == '<deco_name>'%}
        {% set ns.result = ns.result + state_attr(a, 'up_kilobytes_per_s') %}
        {% endfor %}
        {{ ns.result}}
```

Same template sensor for Download (so `'down_kilobytes_per_s'`)  and for all Deco's you have. So in my case; I have 3 Deco devices, so 6 sensors in total.

**Comment by Verguldebarman** [comment]
Just received a yaml from HA community member (thx !!!!), to create the sensor without a FOR statement. 
Might be better:

```
{{ states.device_tracker
   |selectattr('entity_id', 'in', integration_entities('tplink_deco'))
   |selectattr('attributes.deco_device', 'eq', '<deco_name>')
   |map(attribute='attributes.up_kilobytes_per_s')
   |select('number')
   |sum }}
```

**Comment by kaosmagix** [comment]
I would like this feature. However if possible it would be best to retrieve the up/down of the Deco Unit itself instead of calculating it based on the clients.
For the main unit I retrieve the total up/down by the uPNP/IGD integration, but it would be nice not to need an additional integration

**Comment by amosyuen** [comment]
Added in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.5.0
