### ISSUE TITLE
Get which deco device client is connected to

### ISSUE THREAD

**Issue by Devil-of-Chaos** [amosyuen/ha-tplink-deco#17]
**Is your feature request related to a problem? Please describe.**
No it‘s enhancement

**Describe the solution you'd like**
With which deco is the device connected, normally you have more mesh devices. So if Phone A is connected with deco living room and device B connected with deco in the kitchen. 

**Describe alternatives you've considered**
It must not be the label or something else IP or Mac is ok i think

**Comment by amosyuen** [comment]
It looks like this info is not availabe in the list clients API call, most likely would need to do a separate HTTP request for each device. This feature likely will not be a priority.

**Comment by freddieleeman** [comment]
I would love this feature to allow me to detect where a phone (person w/phone) is in the house.

**Comment by Xelinor** [comment]
> I would love this feature to allow me to detect where a phone (person w/phone) is in the house.

That would be REALLY difficult using WiFi. Wifi has a tendency to be 'sticky' and not move with you smoothly. Not to mention if you had a mesh router in every room you are probably causing yourself interference. That's a lot of RF.

**Comment by amosyuen** [comment]
As @Xelinor stated, probably the switching is sticky and slow and in addition my guess would be that it is not very accurate for localization since wifi will go through walls. So you could be upstairs or downstairs, in living room or bedroom. You probably could only get a general sense of left side of the house vs right side of the house.

**Comment by freddieleeman** [comment]
In my situation, this would suffice, as my WiFi covers a lot of ground, it would allow me to accurately detect if I'm in the living quarters or office. While I understand this would not benefit everyone, it would create options for some. However, if this would significantly increase the number of web calls, this is probably not feasible.

**Comment by Xelinor** [comment]
So, and I admit to not having fully baked this idea, but you might try adding multiple deco units to the integration and see if it can actually detect you moving between them?

**Comment by amosyuen** [comment]
Took another look at the admin UI and looks like the only way to figure it out is to go through the list of routers and do a client list call for each router. So not as bad as I thought (needing a request for each client), but requires more requests.

**Comment by n00bcodr** [comment]
This can be achieved for phones with the Wi-Fi BSSID sensor in the companion app.

**Comment by freddieleeman** [comment]
DUDE! I did not know that sensor existed. I enabled it, and it is working perfectly. Thank you!

**Comment by amosyuen** [comment]
This is now available in v1.1.0 thanks to @gdiepen
