### ISSUE TITLE
FR: Optional prefix for entity ids

### ISSUE THREAD

**Issue by michaelblight** [amosyuen/ha-tplink-deco#171]
**Is your feature request related to a problem? Please describe.**
I want both my netgear modem and tp-link m5 routers linked with HA. However, both try to give the entities the same id (eg. `device_tracker.legion5`). Therefore the second one to be installed gets an id of `device_tracker.legion5_2`, which makes it very confusing.

**Describe the solution you'd like**
I would like the setup of the integration to offer an optional prefix for entity ids. Therefore I could enter "deco" and have the above entity instead be called `device_tracker.deco_legion5`.

**Describe alternatives you've considered**
I could manually rename them, but that won't work for new devices (eg. visitors) connecting to wifi.

**Additional context**

**Comment by amosyuen** [comment]
Added in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.4.0
