### ISSUE TITLE
duplicate unique ids

### ISSUE THREAD

**Issue by redlingg** [amosyuen/ha-tplink-deco#188]
### Problem

Platform tplink_deco does not generate unique IDs. ID 68-FF-7B-32-56-A8 already exists - ignoring device_tracker.bedroom_deco
Platform tplink_deco does not generate unique IDs. ID 28-87-BA-88-83-A4 already exists - ignoring device_tracker.hallway_deco

what can be done to resolve these?

### TP-Link Deco Version

v2

### Router Model

deco m4

### Debugging Information

Platform tplink_deco does not generate unique IDs. ID 68-FF-7B-32-56-A8 already exists - ignoring device_tracker.bedroom_deco
Platform tplink_deco does not generate unique IDs. ID 28-87-BA-88-83-A4 already exists - ignoring device_tracker.hallway_deco

**Comment by amosyuen** [comment]
Are there other entities added from those mac addresses from different integrations?

**Comment by redlingg** [comment]
????

**Comment by redlingg** [comment]
..and this is a new one

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 18:33:22 (1 occurrences)
Last logged: 18:33:22

Detected integration that restore_state.RestoreStateData.async_get_instance is deprecated, and not intended to be called by custom components; Pleaserefactor your code to use RestoreEntity instead; restore_state.async_get(hass) can be used in the meantime. Please report issue to the custom integration author for tplink_deco using this method at custom_components/tplink_deco/__init__.py, line 121: last_states = (await RestoreStateData.async_get_instance(hass)).last_states

**Comment by amosyuen** [comment]
Can you answer the above question? Can't help without more info.

**Comment by redlingg** [comment]
not sure what the question is.. these are the MAC addr of the deco routers. no other integration is connected to these devices.

**Comment by amosyuen** [comment]
How did you verify that no integration is connected to those routers? The best way to verify is to look in your `core.entity_registry` file and look for that MAC address.

If you're sure they aren't coming from another integration, then please get debug logs https://github.com/amosyuen/ha-tplink-deco/blob/main/DEBUGGING.md#general-steps.

Also would like info on when you see the errors. e.g. At the integration first setup? Each time integration starts?

**Comment by redlingg** [comment]
ok I dont know where this file is. I have smb installed but dont find it.


Amos Yuen ***@***.***> ezt írta (időpont: 2023. júl. 20., Cs,
23:14):

**Comment by amosyuen** [comment]
Closing because no debug logs

**Comment by redlingg** [comment]
No problem. I did not receive any answer either so I deleted the integration.
