### ISSUE TITLE
Not An issue, a Feedback : Confirmed to work with Deco P7

### ISSUE THREAD

**Issue by FillR2** [amosyuen/ha-tplink-deco#19]
Hi,

I just want to confirm that the integration is working with Deco P7 that can be added to compatibility list.

![image](https://user-images.githubusercontent.com/86425615/150780001-e0bbf52f-3398-44db-a2c7-799cbb8d7d96.png)

![image](https://user-images.githubusercontent.com/86425615/150779814-8271ca76-ce48-4dae-a100-956d7dc924ea.png)

**Comment by amosyuen** [comment]
Thanks for letting me know!

**Comment by ben0551** [comment]
Confirmed working on x20 too
