### ISSUE TITLE
"Failed to set up" error following last update

### ISSUE THREAD

**Issue by antonyslater** [amosyuen/ha-tplink-deco#207]
### Problem

Following the update to v3.5.0 (**Edit** v3.4.1)  my installation fails to start properly meaning all my TPLink Deco entities are unavailable and useless.  I have followed the same update procedure I have done many times before with no issue.

I have tried removing the integration and the underlying HACS custom repository files to no avail.

Running the configuration seems to "work" in that I get a finished successfully message but the integration then still shows as failed.

I have tried increasing the timeout values, which again say they have saved but always revert back to the default 30 seconds with no change to the issue.

### TP-Link Deco Version

v3.5.0 (**Edit** v3.4.1)

### Router Model

Deco E4

### Debugging Information

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tplink_deco/__init__.py:125
Integration: TP-Link Deco (documentation, issues)
First occurred: 11:26:47 (1 occurrences)
Last logged: 11:26:47

Error setting up entry 192.168.1.30 for tplink_deco
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tplink_deco/__init__.py", line 159, in async_setup_entry
    data = await async_create_config_data(hass, config_entry)
  File "/config/custom_components/tplink_deco/__init__.py", line 125, in async_create_config_data
    last_states = restore_state.async_get(hass).last_states
AttributeError: module 'homeassistant.helpers.restore_state' has no attribute 'async_get'

**Comment by antonyslater** [comment]
I have rolled back to the previous version (v3.4.1) this morning as I need the integration to work and noticed that I've actually needed to go back to version v3.4.0 to get it working again, so the issue seems to have been introduced from v3.4.1.  Hope this helps with any diagnosis, please let me know if you need any further information/testing from me.

**Comment by amosyuen** [comment]
What version of HA do you have? Looks like maybe you're running an older version that doesn't support that API

**Comment by gurmukhp** [comment]
I'm on Frontend 20230110.0 - latest and also get this issue

**Comment by gurmukhp** [comment]
Even when rolling back to 3.31 I still get the error:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tplink_deco/__init__.py:125
Integration: TP-Link Deco (documentation, issues)
First occurred: 19:13:46 (2 occurrences)
Last logged: 19:22:53

Error setting up entry 192.168.68.1 for tplink_deco
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tplink_deco/__init__.py", line 159, in async_setup_entry
    data = await async_create_config_data(hass, config_entry)
  File "/config/custom_components/tplink_deco/__init__.py", line 125, in async_create_config_data
    last_states = restore_state.async_get(hass).last_states
AttributeError: module 'homeassistant.helpers.restore_state' has no attribute 'async_get'

**Comment by amosyuen** [comment]
20230110 is january 2023 and so is before 2023.6.0 which is june 2023.

**Comment by antonyslater** [comment]
> What version of HA do you have? Looks like that call was added in [2023.6.0](https://github.com/home-assistant/core/releases/tag/2023.6.0). I can add a version restriction

Hi there, I'm on Home Assistant 2023.5.4 and Frontend 20230503.3

**Comment by gurmukhp** [comment]
Thank you! My Docker install was saying it was up to date, clearly not!

**Comment by amosyuen** [comment]
Set minimum version in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.5.1 so you shouldn't be prompted to update for older installs anymore.
