### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE on setup

### ISSUE THREAD

**Issue by az01101001** [amosyuen/ha-tplink-deco#209]
### Problem

Main Deco: X20
Firmware: 1.0.5 Build 20220812 Rel. 62220
Hardware: 3.0
 
Kept getting `SSLV3_ALERT_HANDSHAKE_FAILURE` when setting up, with and without `verify_ssl`.

Tried to look into it and I believe it has something to do with [Python 3.10 increasing the security of TLS settings by default](https://bugs.python.org/issue43998).

Whipped up a quick fix [here](https://github.com/az01101001/ha-tplink-deco/commit/a9739ab45193d9b1f4daa3b6ffe5a2dd2b11eb2e) and can confirm that it works now, however I am unsure of its security implications.

Also, looks like the `verify_ssl` parameter has been deprecated in favor of `ssl`.

### TP-Link Deco Version

v3.5.0

### Router Model

Deco X20 V3

### Debugging Information

`ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure`

**Comment by amosyuen** [comment]
Thanks for drafting a fix.

From the docs https://docs.aiohttp.org/en/v3.8.5/client_reference.html#aiohttp.ClientSession.request, I see there is an `ssl` parameter, leaving it as `None` should use default behavior, and setting to `False` should disable the SSL check.

**Comment by az01101001** [comment]
Yeah, but simply setting `ssl` to `False` somehow didn't fix the issue.

**Comment by amosyuen** [comment]
Seems strange that `ssl` to `False` doesn't work, but since the core change was similar to yours we can try using yours. My deco requires SSL so I can't test the non-ssl path, hopefully it works with others decos. Did you want to make a PR?

**Comment by az01101001** [comment]
Just double-checked again, can confirm setting `ssl` to `False` doesn't work on my Deco. I'll finalize the changes then do a PR. You're right though, hopefully it doesn't break people's setups.

**Comment by amosyuen** [comment]
Change in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.5.2
