### ISSUE TITLE
device_tracker entities suddenly Unavailable

### ISSUE THREAD

**Issue by rzantengmail** [amosyuen/ha-tplink-deco#224]
### Problem

Since yesterday most of my device_tracker entities returned as Unavailable.

Didn't perform update or changes.

Running HAOS 2023.9.3 with TP-Link Deco v3.5.4.

Reloading the integration and restarting HAOS did not resolve the issue.

What went wrong here?

### TP-Link Deco Version

v3.5.4

### Router Model

Deco X60 (3 pieces) with M4R (3 pieces)

### Debugging Information

Can provide if needed :)

**Comment by leonjehae** [comment]
Same here, since a few hours. Reinstall HACS and DECO integration didn't help either.

**Comment by leonjehae** [comment]
Version 3.5.43 I disabled fast roaming today on the DECO but it worked for a few hours. (Wallbox car charger cannot connect when enabled)

**Comment by rzantengmail** [comment]
Ok guys... I managed to get it working again. Did some tweaks to the configuration and it back in business :)
