### ISSUE TITLE
Integration -> Device -> Entities Hierarchy

### ISSUE THREAD

**Issue by mogodon** [amosyuen/ha-tplink-deco#23]
**Is your feature request related to a problem? Please describe.**
Nope, feature suggestion

**Describe the solution you'd like**
At present the integration has only an entity level and no umbrella device. This makes it hard to add the entities to cards as there is no connection in the naming, other than device_tracker. In the case of phones I already have device trackers set up which is confusing.

**Describe alternatives you've considered**
I can manually rename all of the entities with a prefix of "Deco - " but that needs to be done for each and every new client discovered.

**Additional context**
To be honest I'm not sure what other people are using this for but I'd just like there to be a Deco device, with all of the entities listed from there. Failing that perhaps just prefix the entities with deco automatically, e.g. "device_tracker_samsung_phone" becomes "device_tracker_tplink_deco_samsung_phone" or similar.

Thanks

**Comment by amosyuen** [comment]
Added `device_info` in v1.0.0
