### ISSUE TITLE
Deco S4 - Feedback

### ISSUE THREAD

**Issue by bsimmo** [amosyuen/ha-tplink-deco#25]
Using a TP-Link S4.   v1. 50 firmware
HA on RPi3-64 
core-2021.12.7
supervisor-2021.12.2

Other than needing a reboot and remembering the Deco password.
It seems to be running OK.
(Side note: Upnp/igp also sees it and is giving data stats)

A lot of device trackers created.

**Comment by amosyuen** [comment]
Updated readme in https://github.com/amosyuen/ha-tplink-deco/commit/4ec60f72255fb7560747547419439ea7d81b110e
