### ISSUE TITLE
SOURCE_TYPE_ROUTER deprecated

### ISSUE THREAD

**Issue by dexn** [amosyuen/ha-tplink-deco#251]
### Problem

`SOURCE_TYPE_ROUTER was used from tplink_deco, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead`

### TP-Link Deco Version

NA

### Router Model

NA

### Debugging Information

NA

**Comment by amosyuen** [comment]
Fixed in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.6.
