### ISSUE TITLE
Wrong download value in the attributes

### ISSUE THREAD

**Issue by neuroverflow** [amosyuen/ha-tplink-deco#26]
Hi! 
I noticed you send twice the upload instead of sending the download.
Units seems to to bauds, can we convert them to ko/s or mo/s?

`@property
    def extra_state_attributes(self):
        """Return extra state attributes."""
        return {
            "connection_type": self._client.connection_type,
            "interface": self._client.interface,
            "down_kb_per_s": self._client.up_kb_per_s,
            "up_kb_per_s": self._client.up_kb_per_s,
        }`

**Comment by mogodon** [comment]
Was just about to post this.

**Comment by amosyuen** [comment]
Fixed in v1.0.0
