### ISSUE TITLE
Add KS240 integration

### ISSUE THREAD

**Issue by briadelour** [amosyuen/ha-tplink-deco#280]
**Is your feature request related to a problem? Please describe.**
KS240 is a new type of ceiling fan switch from the TP-Link KASA line that controls, one for the fan speed control and one for light dimmer switch.  This is not getting discovered.

**Describe the solution you'd like**
I have a KS220 switch and KP303 power strip that is getting discovered fine by the integration, the KS240 definition may just need to be added.

**Describe alternatives you've considered**
The device is currently being added to the python-kasa, https://github.com/python-kasa/python-kasa/pull/764, initially reported here: https://github.com/python-kasa/python-kasa/issues/749

**Additional context**
This has also been added as as request to be added to the HA core: https://github.com/home-assistant/core/issues/111238

**Comment by amosyuen** [comment]
This is the repro for tp-link decos. KS249 is not a deco, please go request in the kasa integration
