### ISSUE TITLE
'tplink_deco' calls `async_add_job`, which is deprecated and will be removed

### ISSUE THREAD

**Issue by cloudbr34k84** [amosyuen/ha-tplink-deco#285]
### Problem

Detected that custom integration 'tplink_deco' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/tplink_deco/__init__.py, line 166: hass.async_add_job(, please create a bug report at https://github.com/amosyuen/ha-tplink-deco/issues

### TP-Link Deco Version

X20

### Router Model

X20

### Debugging Information

Detected that custom integration 'tplink_deco' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/tplink_deco/__init__.py, line 166: hass.async_add_job(, please create a bug report at https://github.com/amosyuen/ha-tplink-deco/issues

**Comment by cloudbr34k84** [comment]
wrong area to log issue

**Comment by Beer17HWAM** [comment]
See https://github.com/amosyuen/ha-tplink-deco/issues/278#issuecomment-2092909462
