### ISSUE TITLE
Only Exposing Desired Devices as Entities

### ISSUE THREAD

**Issue by schwieb** [amosyuen/ha-tplink-deco#29]
**Is your feature request related to a problem? Please describe.**
This is just a feature request/suggestion.

**Describe the solution you'd like**
By default, the integration shares all of the connected devices as entities in home assistant.  It would be nice to instead manually expose only the devices you wish to track.  I'm not sure of the overhead on Home Assistant by having all devices show up, but I do know that it adds a lot of unnecessary devices that will never leave the house!

**Describe alternatives you've considered**
I have manually selected all of the entities and 'disabled' them.  I have also disabled the 'enable newly added entities' option to prevent any new devices being automatically added to home assistant. These options cause me issues with the integration being able to get updates from the devices left enabled.

**Comment by amosyuen** [comment]
I don't see much benefit of doing that compared to using HA's ability to enable / disable entities. Could you clarify how disabling `enable newly added entities` causes problems, as that sounds like the desired solution.

**Comment by schwieb** [comment]
I only suggested it because I believe that is how the UniFi integration works.
 
The problem:
If I disable all of the entities, the remaining devices show a status with the 'red ! circle' and dont seem to re-connect.  I am still waiting to see if this remedies itself.

**Comment by schwieb** [comment]
You can close out my request.  The latest HA Core update has seemingly fixed the issue (that could be incidental) and added some improvements to how HA handles these devices.
