### ISSUE TITLE
List of planned features and to-do's

### ISSUE THREAD

**Issue by jeremysherriff** [amosyuen/ha-tplink-deco#31]
**Is your feature request related to a problem? Please describe.**
In the readme that you say "currently the only feature implemented is..." so I'm wondering what else you had in mind for functionality

**Describe the solution you'd like**
A readme section with a list of features and functions that you'd like to implement - to inspire contributors

**Comment by amosyuen** [comment]
There really isn't any planned feature except adding entities for the actual deco units.

**Comment by SLG** [comment]
I was wondering if the API exposes on which Deco unit the device is connected to. I've three Deco's, and thought that I could maybe use this as a simple room-detection utility.

**Comment by amosyuen** [comment]
> I was wondering if the API exposes on which Deco unit the device is connected to. I've three Deco's, and thought that I could maybe use this as a simple room-detection utility.

See [the](https://github.com/amosyuen/ha-tplink-deco/issues/17)
