### ISSUE TITLE
unavailable state for all DECO devices most of the time

### ISSUE THREAD

**Issue by freddieleeman** [amosyuen/ha-tplink-deco#39]
I'm experiencing that all DECO devices report an 'unavailable' status most of the time. Sometimes it works for a few minutes, but not for long. I have 4x TP-Link Deco M4 and around 70 connected devices. I tried to increase the interval, but that doesn't appear to change anything. Is anyone seeing the same thing?

```
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:134
Integration: TP-Link Deco (documentation, issues)
First occurred: 1:38:08 PM (3 occurrences)
Last logged: 1:41:19 PM

Unexpected error fetching tplink_deco data: List devices error None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 90, in _async_update_data
    new_clients = await self._api.async_list_clients()
  File "/config/custom_components/tplink_deco/api.py", line 134, in async_list_clients
    raise Exception(f"List devices error {error_code}")
Exception: List devices error None
```
```
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:152
Integration: TP-Link Deco (documentation, issues)
First occurred: 1:29:03 PM (6 occurrences)
Last logged: 1:40:19 PM

Unexpected error fetching tplink_deco data: List clients error None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 90, in _async_update_data
    new_clients = await self._api.async_list_clients()
  File "/config/custom_components/tplink_deco/api.py", line 152, in async_list_clients
    raise Exception(f"List clients error {error_code}")
Exception: List clients error None

```

**Comment by amosyuen** [comment]
Looks like for some reason the response json does not have an "error_code" attribute. I can try adding more logging to help see what response we are getting from the deco.

**Comment by amosyuen** [comment]
I added more logging in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v1.1.1, which should log the response if you set the logging level to debug. Please copy and past that log.

**Comment by MickW69** [comment]
For what its worth, I am getting the same unavailable status as mentioned above, have just updated HA to 2022.3.3 and updated Deco integration. For the beginners amongst us, "Put code: logging: deco = dubug" into config etc, would be helpful.

**Comment by Gyosa3** [comment]
Hi, I have a setup of 6 P9 decos, some of which are quite unstable so I reboot all of them every night and I wish to monitor their disconnection. 
I am using this integration and had trouble setting it up. First I got "unavailable" permanently then now the decos themselves are "home" when they're connected, while all the client devices are permanently "unavailable".

I've had this error in the log:

`
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 236, in _async_update_data
    deco_client_responses = await asyncio.gather(
  File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 160, in async_list_clients
    data=self._encode_payload(client_payload),
  File "/config/custom_components/tplink_deco/api.py", line 330, in _encode_payload
    sign = self._encode_sign(len(data))
  File "/config/custom_components/tplink_deco/api.py", line 336, in _encode_sign
    seq_with_data_len = self._seq + data_len
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

**Comment by freddieleeman** [comment]
Here is my most recent log entry: 
```
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:167
Integration: TP-Link Deco (documentation, issues)
First occurred: March 14, 2022, 1:01:29 AM (17 occurrences)
Last logged: March 14, 2022, 4:03:40 AM

Unexpected error fetching tplink_deco-clients data: List Clients D8-47-32-A4-E2-40 error None
Unexpected error fetching tplink_deco-clients data: List Clients D8-47-32-A4-E1-80 error None
Unexpected error fetching tplink_deco-clients data: List Clients 28-EE-52-66-C2-F8 error None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 236, in _async_update_data
    deco_client_responses = await asyncio.gather(
  File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 167, in async_list_clients
    raise Exception(f"{context} error {error_code}")
Exception: List Clients D8-47-32-A4-E2-40 error None
```
I haven't had time to enable debug mode yet. I will do that today and see if I can get more details on the issue.

**Comment by freddieleeman** [comment]
Here is te debug data from the log:

```

**Comment by Gyosa3** [comment]
![availability-deco](https://user-images.githubusercontent.com/51777889/158406950-b7d12a08-5927-46db-a88b-13ae1766ab5a.PNG)

Not sure if it helps, here is the history of the availability of the clients. Two bars on top are 2 deco boxes, two bars below are 2 cameras permanently connected in wifi to the Deco network.

refresh time is 90 sec

**Comment by amosyuen** [comment]
403 errors usually mean you are logging in with the admin credentials (in the app or the web portal) while the integration is running. I'm guessing you're logging in with the admin credentials to reset the routers? If so the 403s are expected errors.



The clients are showing up as unavailable because the http call times out. Please try these steps:
1. Disable the integration temporarily
2. Log in to the web portal for the router (not the app)
3. Verify that the list clients works in the web portal
4. Open the browser developer console, go to the network tab, and check how long the list clients call is taking.

We might just need to increase the timeout value. So I can increase it based on how long yours is taking.

**Comment by freddieleeman** [comment]
Here are the results:

Average: 5.18 seconds
Highest: 7.61 seconds
Lowest: 3.66 seconds

What is the current timeout setting?

**Comment by amosyuen** [comment]
Current timeout is 30s, on closer look seems the timeout error is actually a response from the deco, so that seems to indicate it's a timeout on the deco side. You had no problems with listing clients on the web portal?

**Comment by amosyuen** [comment]
Not clear to me why the deco is returning timeout with such a short timeout, but since that's on their side not much I can do. I added code to retry if that case happens. Hopefully that helps mitigate the problem a little.

**Comment by bachoo786** [comment]
Hi I am also facing similar issues as the devices on my deco m5 are not home/not connected to my deco m5 are showing as 'unavailable' rather than 'away' or 'not_home'.

This is messing up my automations and they fail to trigger due to this. 

Can this be please looked into ?

Thanks

**Comment by chrisdeman** [comment]
The latest update fixed this problem for me
