### ISSUE TITLE
Reboot all deco devices

### ISSUE THREAD

**Issue by mousawm** [amosyuen/ha-tplink-deco#50]
**Is your feature request related to a problem? Please describe.**
this integration uses the owner account and there is no option to reboot all deco devices when using manager account.

**Describe the solution you'd like**
as [amosyuen](https://github.com/amosyuen) suggested [here](https://github.com/amosyuen/ha-tplink-deco/issues/46#issuecomment-1061191424) that the web admin portal has the ability to reboot specific devices or all devices. 

**Additional context**
it will be nice to have the option to be able to reboot a specific deco device or all devices within home assistant.

**Comment by amosyuen** [comment]
Reboot deco service added in release https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.1.0

**Comment by mousawm** [comment]
@amosyuen thanks :)
