### ISSUE TITLE
Update and search for connected devices

### ISSUE THREAD

**Issue by pex81** [amosyuen/ha-tplink-deco#52]
Hi, I'm running your custom component with 3 Deco P9 connect and detect the device_trackers.
But when a device disconnects and then reconnects, the state of the device does not change until I open the HA app.
It's normal?

## Version
HA 2022.3.3
[ha-tplink-deco](https://github.com/amosyuen/ha-tplink-deco) 2.0.2
 
## Configuration, I also waited for the time indicated in the configuration.
<img width="589" alt="Schermata 2022-03-11 alle 13 18 27" src="https://user-images.githubusercontent.com/58252398/157866037-55010518-67bb-45e7-a97f-0992e3c93722.png">

## Ping work
<img width="592" alt="Schermata 2022-03-11 alle 13 18 51" src="https://user-images.githubusercontent.com/58252398/157866066-5d6b1911-37f9-440d-be7d-fcdbb024bbf0.png">

## But state is not_home
<img width="345" alt="Schermata 2022-03-11 alle 13 19 30" src="https://user-images.githubusercontent.com/58252398/157866096-50495f57-2bb2-449c-a77b-3e96527c9c02.png">

**Comment by amosyuen** [comment]
The app should not affect it, but there is an expected delay in update since this is a polling integration. It depends on how often it updates. e.g. the "Seconds between updates" setting. So it may take 30s + how long it takes to make the requests to update.
