### ISSUE TITLE
node red and reboot deco bug

### ISSUE THREAD

**Issue by mousawm** [amosyuen/ha-tplink-deco#59]
## Versions
ha-tplink-deco: 2.1
core: 2022.3.8
supervisor: 2022.03.5
Home Assistant OS: 7.6

## Describe the bug

with home assistant automation I can use reboot 1 deco without problem but with node red I get an error "Call-service error. expected a list for dictionary value @ data['entity_id']", but when I set 2 decos in node red I don't get that error and it reboot the decos, not sure what the problem.

**Comment by amosyuen** [comment]
Sounds like node red is setting the entity_id to a singleton value. Not familiar with node red, please see if you can modify it to set it as a list of a single value.

**Comment by mousawm** [comment]
> Sounds like node red is setting the entity_id to a singleton value. Not familiar with node red, please see if you can modify it to set it as a list of a single value.

Hi, I tried, but I'm not sure if that possible, so my work around is to create an automation in home assistant and trigger it from node red. until I find a better solution to make all the part of automation inside node red.

btw: do you know how to use connected device status "Home" or "Away" in condition inside home assistant automation?

**Comment by amosyuen** [comment]
Closing this as WAI as it sounds like a node-red thing. To use device_tracker in automation just check if state is "home" or "not_home"

**Comment by mousawm** [comment]
thanks for help

**Comment by mousawm** [comment]
Hi,

I got it solved with the following code in the function node:

```
if (msg.payload === "test") 
    msg.payload = {"entity_id":["device_tracker.roof_deco"]};
return msg;
```

and adding this code in the data section in the call service as JSON:

`{"entity_id":["{{payload.entity_id}}"]}`

for more information see [here](https://community.home-assistant.io/t/solved-use-list-of-entity-ids-in-call-service-node/409251/7)
