### ISSUE TITLE
Devices from other integrations

### ISSUE THREAD

**Issue by larronni** [amosyuen/ha-tplink-deco#73]
It looks like a lot of devices gets multiple integrations somehow. 
When checking for TP-link Deco device integration, I get a lot of different devices as well.
I only have 3 TP-link devices, but it looks like I have 15 in the overview
![image](https://user-images.githubusercontent.com/49139069/171838300-7e5a86dc-13eb-49fa-97b3-626c9751bb63.png)

When checking the details, I see that a lot of other integrations/devices are mixed in here as well..?
![image](https://user-images.githubusercontent.com/49139069/171838239-57e033e0-df43-48e1-9624-7ee32e903a45.png)

**Comment by amosyuen** [comment]
This is currently how home assistant works. If you don't like it you should file a bug with them.

Most likely you have some of the same entities exposed in other integrations. The entities are keyed by mac address, so if you have a different integration that also exposes entities keyed by the same mac address home assistant will "combine" them. And the iRobot devices will show up in the TP-Link Deco list.
