### ISSUE TITLE
CONECTION HA LOST

### ISSUE THREAD

**Issue by VITCHEPF** [amosyuen/ha-tplink-deco#79]
## Deco modelo
DECO X20 Master

## Describe the bug

HOME ASSISTANT VERSION 2022.7.0b2

TPLINK integration lost connection with HA.
I deleted and reinstalled, but I can't send the configuration because there is an "unexpected error"

## Debug log

```text

Add your debug logs here.

```

**Comment by amosyuen** [comment]
Add debug logs. See https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by VITCHEPF** [comment]
It was necessary downgrade the home assistant, to have the TPlink integration back.

But now the error code=-5003 appeared, and I can't login.

All Device Tracker are Unavailable.


![Screenshot_20220705-230523~2](https://user-images.githubusercontent.com/73760504/177453597-1b666df6-9729-491c-b275-da619c357b79.jpg)

The password still the same, and the IP is from the main Deco in the mesh Network.

**Comment by amosyuen** [comment]
I can not help triage further unless you add debug logs as instructed.
