### ISSUE TITLE
Error while processing event 

### ISSUE THREAD

**Issue by buhito81** [amosyuen/ha-tplink-deco#85]
Repeated errors because, apparently, there IP addresses are left empty.

## Version of the custom_component
2.1.1

## Deco Model
M5

## Describe the bug
Error while processing event 

## Debug log

Logger: homeassistant.helpers.event
Source: components/dhcp/__init__.py:155
First occurred: 09:33:45 (1 occurrences)
Last logged: 09:33:45

Error while processing event <Event state_changed[L]: entity_id=device_tracker.wlan0_3, old_state=None, new_state=<state device_tracker.wlan0_3=home; source_type=router, ip=, mac=38-1F-8D-34-A0-B7, connection_type=band2_4, interface=main, down_kilobytes_per_s=0.0, up_kilobytes_per_s=0.0, deco_device=Living Room, deco_mac=74-DA-88-FE-C5-34, device_class=client, icon=mdi:lan-connect, friendly_name=wlan0 @ 2022-07-19T09:33:44.895347+02:00>> for domain device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 419, in _async_dispatch_domain_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 546, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 311, in _async_process_device_event
    self._async_process_device_state(event.data["new_state"])
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 331, in _async_process_device_state
    self.async_process_client(ip_address, hostname, _format_mac(mac_address))
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 155, in async_process_client
    made_ip_address = make_ip_address(ip_address)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: '' does not appear to be an IPv4 or IPv6 address

**Comment by buhito81** [comment]
[home-assistant.log](https://github.com/amosyuen/ha-tplink-deco/files/9146945/home-assistant.log)

**Comment by amosyuen** [comment]
Looks like the code needs to filter out empty string ip addresses

**Comment by amosyuen** [comment]
Please give https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.1.2 a try

**Comment by buhito81** [comment]
Wow, that's fast, Almost, I guess (this is 2.1.2):

Logger: homeassistant.helpers.event
Source: components/dhcp/__init__.py:155
First occurred: 10:02:57 (1 occurrences)
Last logged: 10:02:57

Error while processing event <Event state_changed[L]: entity_id=device_tracker.wlan0_3, old_state=None, new_state=<state device_tracker.wlan0_3=home; source_type=router, ip=, mac=38-1F-8D-34-A0-B7, connection_type=band2_4, interface=main, down_kilobytes_per_s=0.0, up_kilobytes_per_s=0.0, deco_device=Living Room, deco_mac=74-DA-88-FE-C5-34, device_class=client, icon=mdi:lan-connect, friendly_name=wlan0 @ 2022-07-20T10:02:57.960839+02:00>> for domain device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 419, in _async_dispatch_domain_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 546, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 311, in _async_process_device_event
    self._async_process_device_state(event.data["new_state"])
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 331, in _async_process_device_state
    self.async_process_client(ip_address, hostname, _format_mac(mac_address))
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 155, in async_process_client
    made_ip_address = make_ip_address(ip_address)
  File "/usr/local/lib/python3.10/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: '' does not appear to be an IPv4 or IPv6 address

**Comment by buhito81** [comment]
[home-assistant.log](https://github.com/amosyuen/ha-tplink-deco/files/9148156/home-assistant.log)

**Comment by amosyuen** [comment]
On closer look, it seems like the error is coming from the homeassistant DHCP component. It might be merging the state because both device_trackers have the same MAC. But I don't think there's much more I can do here. I would recommend filing a bug to home assistant core.

What also might be worth investigating is why your client has no IP address.

**Comment by buhito81** [comment]
Thanks for your reply. A few things that crossed my mind:

- Does (the) TP-LINK (integration) assume that there is only one DHCP acting in the network? I.e. if the DHCP is lease is not from the TP-LINK DHCP server, is the IP therefor not available via the TP-LINK api?
- This error appears to have started to occur after firmware update 1.6.0 Build 20220525 Rel.48298 (coincidentally, that also about the time HA 2022.7.x came out)

**Comment by amosyuen** [comment]
The TP-Link integration has no assumptions about DHCP because it doesn't use it. All the TP-Link integration knows is the data it gets from the router API call.
