### ISSUE TITLE
Option to keep last state instead of becoming unavailable

### ISSUE THREAD

**Issue by cvroque** [amosyuen/ha-tplink-deco#95]
**Is your feature request related to a problem? Please describe.**
I have a similar problem to the ones reported in issue #39 and #61. 
![image](https://user-images.githubusercontent.com/65680394/182952604-c917689d-7e93-49e1-9176-df7a73a3e1c2.png)

Sometimes my Deco will timeout and then everything will go unavailable and then recover their status on the next try. This results in dozens of devices becoming home or away in a short period of time, which is bad for some automation or guests detection.
Here's an example:

![image](https://user-images.githubusercontent.com/65680394/182951990-f7de3e4e-374e-42c3-8408-3b3a3c858801.png)

**Describe the solution you'd like**
Instead of devices going unavailable I'd like an option for the devices to keep their last know state when there's an error during status retrieval.

**Describe alternatives you've considered**
I've created a simple template for some device trackers, but it's not a good idea to create dozens of these.

**Additional context**
 I believe this would make the integration work in a more stable manner, even if the fault is on the Deco devices.

**Comment by bachoo786** [comment]
Hi I am also facing similar issues as the devices on my deco m5 are not home/not connected to my deco m5 are showing as 'unavailable' rather than 'away' or 'not_home'.

This is messing up my automations and they fail to trigger due to this. 

Can this be please looked into ?

**Comment by Anonymoesje** [comment]
Same issue, this also messes up the group property, because if one goes unknown/unavailable it will report the whole group as offline.

**Comment by freddieleeman** [comment]
This would help resolve some issues for me too! I would love this as an option, especially to check which AP the client was connected to last (before being unavailable). I know this can be achieved with an SQL sensor, but having it as a feature would be great.

![image](https://user-images.githubusercontent.com/6225998/194234740-88846879-e07c-479f-9798-77b0e5b155a3.png)

**Comment by cvroque** [comment]
> This would help resolve some issues for me too! I would love this as an option, especially to check which AP the client was connected to last (before being unavailable). I know this can be achieved with an SQL sensor, but having it as a feature would be great.
> 
> ![image](https://user-images.githubusercontent.com/6225998/194234740-88846879-e07c-479f-9798-77b0e5b155a3.png)

Hello, your issue really seems similar! After checking the logs, I noticed sometimes that my Deco M4 takes over 30 seconds to return the device list, sometimes even going as high as 50 seconds.

Try and change line 26 on the file api.py from 30 to 60 or higher.

`TIMEOUT = 60`

I made this change recently, I'm still testing, but it seems to have "fixed" my issues.

![image](https://user-images.githubusercontent.com/65680394/194551130-360b1b67-1956-4fec-b07e-07e529a12725.png)

**Comment by freddieleeman** [comment]
Thank you for taking the time to answer me. I'll give your suggestion a try. I also have Deco M4 units, and a timeout is a likely cause. If this resolves my issue, I will create a PR to increase the default timeout value. Thanks again!

**Comment by cvroque** [comment]
> Thank you for taking the time to answer me. I'll give your suggestion a try. I also have Deco M4 units, and a timeout is a likely cause. If this resolves my issue, I will create a PR to increase the default timeout value. Thanks again!

I believe a PR that allows this value to be changed from the UI will be better.

I'm just testing over the weekend before making the PR. Let me know if this fixes it for you as well!

**Comment by freddieleeman** [comment]
Unfortunately, so far, the results are not good:

![image](https://user-images.githubusercontent.com/6225998/194572481-9953577c-dd90-4da5-b641-a8c32e122e71.png)

I've increased to 90, but so far the results are still disappointing. 

```
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:215
Integration: TP-Link Deco ([documentation](https://github.com/amosyuen/ha-tplink-deco), [issues](https://github.com/amosyuen/ha-tplink-deco/issues))
First occurred: 15:31:18 (120 occurrences)
Last logged: 16:04:32

    List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
    List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
    List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
    List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
    List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
```

**Comment by cvroque** [comment]
> Unfortunately, so far, the results are not good:
> 
> ![image](https://user-images.githubusercontent.com/6225998/194572481-9953577c-dd90-4da5-b641-a8c32e122e71.png)
> 
> I've increased to 90, but so far the results are still disappointing.
> 
> ```
> Logger: custom_components.tplink_deco
> Source: custom_components/tplink_deco/api.py:215
> Integration: TP-Link Deco ([documentation](https://github.com/amosyuen/ha-tplink-deco), [issues](https://github.com/amosyuen/ha-tplink-deco/issues))
> First occurred: 15:31:18 (120 occurrences)
> Last logged: 16:04:32
> 
>     List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
>     List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
>     List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
>     List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
>     List Clients <snip> parse response error='result', data={'success': False, 'errorcode': 'timeout'}
> ```

In that case you need to enable debug options and check out what's happening.

Mine had stuff like this:

> 	Line 807: 2022-10-07 10:03:46.419 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 27.419 seconds (success: True)
	Line 835: 2022-10-07 10:04:45.560 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 29.560 seconds (success: True)
	Line 846: 2022-10-07 10:06:15.013 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 60.011 seconds (success: False)
	Line 856: 2022-10-07 10:07:01.797 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 16.796 seconds (success: True)

**Comment by amosyuen** [comment]
Timeout seconds and timeout retries config has been added as a mitigation in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0
