### ISSUE TITLE
Error when trying to configure.

### ISSUE THREAD

**Issue by itnassol** [amosyuen/ha-tplink-deco#97]
I go to add integration, add the TP-Link Deco, change the IP to 192.168.68.1 (Which is my IP) add my password and click submit.

The submit changes to a lopping gif, that lasts about 2 minutes, it then come back with the error below.
![Settings_–_Home_Assistant_-_2022-08-22_13 22 21](https://user-images.githubusercontent.com/26282121/185925979-79e7ae8a-f305-4ae6-aa5f-24e6aff00dcb.png)
The only Errors in the log are
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:81
Integration: TP-Link Deco (documentation, issues)
First occurred: 13:53:26 (1 occurrences)
Last logged: 13:53:26

Error testing credentials:

**Comment by EkielZan** [comment]
Yes, the Same issues here. Posting to raise the issue and follow up

**Comment by amosyuen** [comment]
Please follow steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by itnassol** [comment]
> Please follow steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md
[Deco_Error_Log.txt](https://github.com/amosyuen/ha-tplink-deco/files/9414202/Deco_Error_Log.txt)

Hi there I followed those steps very carefully, adding the lines to the yaml and the re-trying as suggested, same problem, the logs do not mention, that I can see, Error response from router or Timed out.

I have attached them, for you to look at, I a very new to HA.

Thank you so far for the advise.

**Comment by renslinden** [comment]
I had the same issue, restarting all Decos solved it. Can you try it too?

**Comment by itnassol** [comment]
Did you do them 1 at a time or a mas restart?

**Comment by renslinden** [comment]
I rebooted the main one from the Deco app. Don't think it matter whether the rest is rebooted or not because the main one is needed for HA connection.

**Comment by itnassol** [comment]
Thank you I will give it a try now. Can I ask you a question? On my web login for the Deco the main Deco is 192.168.68.1, but the others are 192.168.**71**.XX. My knowledge of IP and subnets is very basic.

**Comment by renslinden** [comment]
That's weird indeed. What is your subnetmask?
If it is 255.255.255.0 then I expect them all in the same range eg. 192.168.68.x. Otherwise it can't work as expected. If it is like 255.255.0.0 then it is fine.

**Comment by itnassol** [comment]
That's what I am thinking, the details are 
Subnet Mask:
255.255.240.0
Primary DNS:
194.168.4.100
Secondary DNS:
194.168.8.100

Do you think a rebuild of the mesh might be in order?

**Comment by renslinden** [comment]
For simplicity let's try to change the subnet to 255.255.255.0 and see what happens with the other Decos. I guess they will get a new IP address in the same range as the Main one. 

Don't forget to set DHCP in the correct range for example 192.168.68.100 to 192.168.68.200. That might be enough for all your devices.

Mind that all your devices might lose connectivity for some time while requesting a new IP address.

Good luck!

One other question, are you able to open the web interface of 192.168.68.1 in a browser and are you able to login?

**Comment by itnassol** [comment]
Firstly let me thank you for all your help, yes I can get in from the web UI, logs in and shows everything, there are 8 nodes and 75 devices on the system. I will try what you suggested and let you know the outcome. Cheers again.

**Comment by itnassol** [comment]
Unfortunately still no luck the logs now say..

```
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:81
Integration: TP-Link Deco (documentation, issues)
First occurred: 24 August 2022 at 14:26:50 (9 occurrences)
Last logged: 09:28:06

Error testing credentials:
Error testing credentials: Invalid login credentials. 8 attempts remaining.
Error testing credentials: Invalid login credentials. 6 attempts remaining.
```
Thank you again.

**Comment by renslinden** [comment]
Mmm that's strange.. regarding the logging it is related with authentication. You're sure that the web interface works with the same password?

What I can imagine is that there is an unsupported character in your password which can't be handled by HA? Just a guess... Let's try to change it.

**Comment by itnassol** [comment]
I got all hopeful there, but no, still doing the same thing. Thanks for all your help. Do you have a buy me a coffee?? 

Changed the password to something simple, but the same results, is HA good with mesh systems?

**Comment by amosyuen** [comment]
> Changed the password to something simple, but the same results, is HA good with mesh systems?

Doesn't matter if it's mesh, the integration just logs into the admin portal. As has been said the error usually means username or password is incorrect. Want to verify that you are using the IP address of the base unit?

What model has your deco?
Do you have any unique network settings that could affect ha connecting to it?

It's also possible that your model has different logic. You can try doing the advanced debugging steps in https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md

**Comment by itnassol** [comment]
So I can definitely log into the main unit and that is 192.168.68.1 (as below)

![SKYF0569-5G-1_-_2022-08-26_16 24 31](https://user-images.githubusercontent.com/26282121/186939499-afa831f9-adab-4c76-aa71-7ceb85893a60.png)

The password is very simple and I followed the debugging list and there is nothing like that happening. 

I tried with all extensions removed, just in case. Over the weekend I am going to reset the main Deco to see if that helps, they are X20's by the way.

**Comment by jjvelar** [comment]
Same issue here. Any additional suggestion?

**Comment by amosyuen** [comment]
> I followed the debugging list and there is nothing like that happening.

What do you mean that you followed the debugging list? The debugging instructions specifically ask you to inspect the http commands and copy the decoded payload to this bug. For your case it should be the `login` call.

**Comment by itnassol** [comment]
Sorry forgot to paste results across, I got sent away for work, will be away for a few days, as soon as I am back I will repeat the process and let you know.

**Comment by itnassol** [comment]
Sorry for the delay, had to sort out a family death, I have tried the new updated version, works like a dream thank you.
